//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DanielWillett.ModularRpcs.NamedPipes.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DanielWillett.ModularRpcs.NamedPipes.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception encountered while connecting to a client connection..
        /// </summary>
        internal static string LogErrorConnectingClientToServer {
            get {
                return ResourceManager.GetString("LogErrorConnectingClientToServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception encountered while reading from a pipe stream..
        /// </summary>
        internal static string LogErrorReadingFromPipeStream {
            get {
                return ResourceManager.GetString("LogErrorReadingFromPipeStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception encountered while writing to a pipe stream..
        /// </summary>
        internal static string LogErrorWritingToPipeStream {
            get {
                return ResourceManager.GetString("LogErrorWritingToPipeStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception encountered while disconnecting pipe stream..
        /// </summary>
        internal static string LogWarningDisconnectingPipeStream {
            get {
                return ResourceManager.GetString("LogWarningDisconnectingPipeStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception encountered while reconnecting to a pipe stream server..
        /// </summary>
        internal static string LogWarningReconnectingToPipeStream {
            get {
                return ResourceManager.GetString("LogWarningReconnectingToPipeStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pipe name was not supplied or was invalid..
        /// </summary>
        internal static string MissingOrInvalidPipeName {
            get {
                return ResourceManager.GetString("MissingOrInvalidPipeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Named pipe server name can not be empty..
        /// </summary>
        internal static string MissingOrInvalidPipeServerName {
            get {
                return ResourceManager.GetString("MissingOrInvalidPipeServerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This server has already been started once..
        /// </summary>
        internal static string NamedPipeServerAlreadyStarted {
            get {
                return ResourceManager.GetString("NamedPipeServerAlreadyStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This server has already been started. It&apos;s properties can no longer be changed..
        /// </summary>
        internal static string NamedPipeServerAlreadyStartedImmutableProperties {
            get {
                return ResourceManager.GetString("NamedPipeServerAlreadyStartedImmutableProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This server was never started..
        /// </summary>
        internal static string NamedPipeServerNotStarted {
            get {
                return ResourceManager.GetString("NamedPipeServerNotStarted", resourceCulture);
            }
        }
    }
}
