//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DanielWillett.ModularRpcs.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Logging {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Logging() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DanielWillett.ModularRpcs.Properties.Logging", typeof(Logging).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find a backing field for the identifier of type &apos;{0}&apos;. This is not an error. Consider annotating the backing field with the RpcIdentifierBackingFieldAttribute or the property with the RpcDontUseBackingFieldAttribute..
        /// </summary>
        internal static string BackingFieldNotFound {
            get {
                return ResourceManager.GetString("BackingFieldNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The backing field in type &apos;{0}&apos; annoted with the RpcIdentifierBackingFieldAttribute is not of a valid type, is ignored, or isn&apos;t accessible from the parent class..
        /// </summary>
        internal static string BackingFieldNotValid {
            get {
                return ResourceManager.GetString("BackingFieldNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The base release method in type &apos;{0}&apos; must be a virtual protected method. Use the IgnoreAttribute to ignore the base method and suppress this message..
        /// </summary>
        internal static string BaseReleaseMethodCantBePublic {
            get {
                return ResourceManager.GetString("BaseReleaseMethodCantBePublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The constructor with arguments {0} in type &apos;{1}&apos; is not accessible by the proxy class..
        /// </summary>
        internal static string ConstructorNotVisibileToOverridingClasses {
            get {
                return ResourceManager.GetString("ConstructorNotVisibileToOverridingClasses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generated invoke method target not found in {0}: \&quot;{1}\&quot;..
        /// </summary>
        internal static string GeneratedInvokeMethodTargetNotFound {
            get {
                return ResourceManager.GetString("GeneratedInvokeMethodTargetNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generated invoke method not found in {0}: \&quot;{1}\&quot;..
        /// </summary>
        internal static string GenerateInvokeMethodImplementationNotFound {
            get {
                return ResourceManager.GetString("GenerateInvokeMethodImplementationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The method &apos;{0}&apos; in type &apos;{1}&apos; is not accessible or overridable by the proxy class..
        /// </summary>
        internal static string MethodNotVisibileToOverridingClasses {
            get {
                return ResourceManager.GetString("MethodNotVisibileToOverridingClasses", resourceCulture);
            }
        }
    }
}
